### ISSUE TITLE
For `cronie.sh`, add handling of parameters provided after image type

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion#140]
Currently,  when running `cronie.sh`, the image type must be given last: if any argument is given after, it is interpreted as  image type, failing to build.

For example, .`./cronie.sh -m qemux86-64 -v qemu  mion-image-onlpv1 -e` results in `Nothing PROVIDES 'mion-image-onlpv1 -e'.`

**Comment by johntoomey** [comment]
@kprosise - i took a look at this and i dont think there is an easy way to improve this without adding a lot of code due to the way that the shell getopts thingy works.. so, my suggestion is that we could make sure that its clear in the docs how this is used and possibly add a line to the scripts help function to make it clear that the image must be the last argument - what do you think?

**Comment by kprosise** [comment]
That's fine! It should already be mentioned in the docs, though I'll check what exactly it says and clean it up if needed. I'm also happy to add a line to the scripts help bit.

**Comment by johntoomey** [comment]
Ok - im going to make a call on this one and say that we leave the script the way it is. if someone in the community has an issue and wants to log it we will take another issue but this really is s'posed to be a simple helper script and it is clear from the help output how it is intended to be used..
